name: Deploy Client Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # change to match your version

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Check if 'deploy' branch exists
      id: check_branch
      run: |
        if git ls-remote --heads origin deploy | grep deploy; then
          echo "branch_exists=true" >> $GITHUB_ENV
        else
          echo "branch_exists=false" >> $GITHUB_ENV
        fi

    - name: Create deploy branch if it doesn't exist
      if: env.branch_exists == 'false'
      run: |
        git checkout --orphan deploy
        git reset --hard
        git commit --allow-empty -m "Initialize deploy branch"
        git push origin deploy

    - name: Deploy /build/client folder to deploy branch
      run: |
        # Make a clean working directory
        mkdir temp-deploy
        cp -r build/client/* temp-deploy/
        cd temp-deploy

        git init
        git remote add origin https://github.com/${{ github.repository }}.git
        git checkout -b deploy
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Deploy client build from main"
        git push --force origin deploy
